name: berry
version: 1.0.0
usage: "Example plugin for Helm"
description: "This plugin demonstrates how to create a plugin for Helm"
ignoreFlags: false
platformCommand:
  - os: "darwin"
    arch: "arm64"
    command: "${HELM_PLUGIN_DIR}/scripts/run.sh"
  - os: "linux"
    arch: "amd64"
    command: "${HELM_PLUGIN_DIR}/scripts/run.sh"
  - os: "linux"
    arch: "arm64"
    command: "${HELM_PLUGIN_DIR}/scripts/run.sh"
